# SonarCloud configuration - Chaturbhujaplots SalesTool - Dashboard Services
sonar.projectKey=sushmano-digivista_Chaturbhujaplots-SalesTool-BE-DasboardServices
sonar.organization=sushmano-digivista

sonar.projectName=Chaturbhujaplots SalesTool - Dashboard Services
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/__tests__/**,**/*.test.*,**/*.spec.*,**/coverage/**

sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=false
