server.port=8082
spring.application.name=dashboard-service

spring.data.mongodb.uri=mongodb+srv://Vercel-Admin-ChaturbujaPlots:QsDNB4d3fwNt4wV2@chaturbujaplots.np9kef5.mongodb.net/anjana_dashboard?retryWrites=true&w=majority
spring.data.mongodb.database=anjana_dashboard

app.jwt.secret=DashB0@rdS3rv!ceK3y2025Anjana$ecret
app.jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:3000,http://localhost:3001
app.plot-service.url=http://localhost:8083
app.common-service.url=http://localhost:8081

management.endpoints.web.exposure.include=health,info